// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Example.proto

package com.kerpow.games.packets.example;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ExamplePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kerpow.games.net.common.ExamplePacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string ex1 = 1;</code>
     */
    boolean hasEx1();
    /**
     * <code>required string ex1 = 1;</code>
     */
    java.lang.String getEx1();
    /**
     * <code>required string ex1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getEx1Bytes();

    /**
     * <code>required int32 ex2 = 2;</code>
     */
    boolean hasEx2();
    /**
     * <code>required int32 ex2 = 2;</code>
     */
    int getEx2();
  }
  /**
   * Protobuf type {@code com.kerpow.games.net.common.ExamplePacket}
   */
  public static final class ExamplePacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.kerpow.games.net.common.ExamplePacket)
      ExamplePacketOrBuilder {
    // Use ExamplePacket.newBuilder() to construct.
    private ExamplePacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExamplePacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExamplePacket defaultInstance;
    public static ExamplePacket getDefaultInstance() {
      return defaultInstance;
    }

    public ExamplePacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExamplePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              ex1_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ex2_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kerpow.games.packets.example.Example.internal_static_com_kerpow_games_net_common_ExamplePacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kerpow.games.packets.example.Example.internal_static_com_kerpow_games_net_common_ExamplePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kerpow.games.packets.example.Example.ExamplePacket.class, com.kerpow.games.packets.example.Example.ExamplePacket.Builder.class);
    }

    public static com.google.protobuf.Parser<ExamplePacket> PARSER =
        new com.google.protobuf.AbstractParser<ExamplePacket>() {
      public ExamplePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExamplePacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExamplePacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int EX1_FIELD_NUMBER = 1;
    private java.lang.Object ex1_;
    /**
     * <code>required string ex1 = 1;</code>
     */
    public boolean hasEx1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ex1 = 1;</code>
     */
    public java.lang.String getEx1() {
      java.lang.Object ref = ex1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ex1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ex1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEx1Bytes() {
      java.lang.Object ref = ex1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ex1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EX2_FIELD_NUMBER = 2;
    private int ex2_;
    /**
     * <code>required int32 ex2 = 2;</code>
     */
    public boolean hasEx2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 ex2 = 2;</code>
     */
    public int getEx2() {
      return ex2_;
    }

    private void initFields() {
      ex1_ = "";
      ex2_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEx1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEx2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEx1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ex2_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEx1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ex2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kerpow.games.packets.example.Example.ExamplePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kerpow.games.packets.example.Example.ExamplePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kerpow.games.packets.example.Example.ExamplePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kerpow.games.packets.example.Example.ExamplePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kerpow.games.packets.example.Example.ExamplePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kerpow.games.packets.example.Example.ExamplePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kerpow.games.packets.example.Example.ExamplePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kerpow.games.packets.example.Example.ExamplePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kerpow.games.packets.example.Example.ExamplePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kerpow.games.packets.example.Example.ExamplePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kerpow.games.packets.example.Example.ExamplePacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kerpow.games.net.common.ExamplePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kerpow.games.net.common.ExamplePacket)
        com.kerpow.games.packets.example.Example.ExamplePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kerpow.games.packets.example.Example.internal_static_com_kerpow_games_net_common_ExamplePacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kerpow.games.packets.example.Example.internal_static_com_kerpow_games_net_common_ExamplePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kerpow.games.packets.example.Example.ExamplePacket.class, com.kerpow.games.packets.example.Example.ExamplePacket.Builder.class);
      }

      // Construct using com.kerpow.games.packets.example.Example.ExamplePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ex1_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ex2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kerpow.games.packets.example.Example.internal_static_com_kerpow_games_net_common_ExamplePacket_descriptor;
      }

      public com.kerpow.games.packets.example.Example.ExamplePacket getDefaultInstanceForType() {
        return com.kerpow.games.packets.example.Example.ExamplePacket.getDefaultInstance();
      }

      public com.kerpow.games.packets.example.Example.ExamplePacket build() {
        com.kerpow.games.packets.example.Example.ExamplePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kerpow.games.packets.example.Example.ExamplePacket buildPartial() {
        com.kerpow.games.packets.example.Example.ExamplePacket result = new com.kerpow.games.packets.example.Example.ExamplePacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ex1_ = ex1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ex2_ = ex2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kerpow.games.packets.example.Example.ExamplePacket) {
          return mergeFrom((com.kerpow.games.packets.example.Example.ExamplePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kerpow.games.packets.example.Example.ExamplePacket other) {
        if (other == com.kerpow.games.packets.example.Example.ExamplePacket.getDefaultInstance()) return this;
        if (other.hasEx1()) {
          bitField0_ |= 0x00000001;
          ex1_ = other.ex1_;
          onChanged();
        }
        if (other.hasEx2()) {
          setEx2(other.getEx2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEx1()) {
          
          return false;
        }
        if (!hasEx2()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kerpow.games.packets.example.Example.ExamplePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kerpow.games.packets.example.Example.ExamplePacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object ex1_ = "";
      /**
       * <code>required string ex1 = 1;</code>
       */
      public boolean hasEx1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ex1 = 1;</code>
       */
      public java.lang.String getEx1() {
        java.lang.Object ref = ex1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ex1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ex1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEx1Bytes() {
        java.lang.Object ref = ex1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ex1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ex1 = 1;</code>
       */
      public Builder setEx1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ex1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ex1 = 1;</code>
       */
      public Builder clearEx1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ex1_ = getDefaultInstance().getEx1();
        onChanged();
        return this;
      }
      /**
       * <code>required string ex1 = 1;</code>
       */
      public Builder setEx1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ex1_ = value;
        onChanged();
        return this;
      }

      private int ex2_ ;
      /**
       * <code>required int32 ex2 = 2;</code>
       */
      public boolean hasEx2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 ex2 = 2;</code>
       */
      public int getEx2() {
        return ex2_;
      }
      /**
       * <code>required int32 ex2 = 2;</code>
       */
      public Builder setEx2(int value) {
        bitField0_ |= 0x00000002;
        ex2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ex2 = 2;</code>
       */
      public Builder clearEx2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ex2_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.kerpow.games.net.common.ExamplePacket)
    }

    static {
      defaultInstance = new ExamplePacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.kerpow.games.net.common.ExamplePacket)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kerpow_games_net_common_ExamplePacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kerpow_games_net_common_ExamplePacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rExample.proto\022\033com.kerpow.games.net.co" +
      "mmon\")\n\rExamplePacket\022\013\n\003ex1\030\001 \002(\t\022\013\n\003ex" +
      "2\030\002 \002(\005B\"\n com.kerpow.games.packets.exam" +
      "ple"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_kerpow_games_net_common_ExamplePacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kerpow_games_net_common_ExamplePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_kerpow_games_net_common_ExamplePacket_descriptor,
        new java.lang.String[] { "Ex1", "Ex2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
